Update patch set 1
Patch Set 1: Verified-1

SEVERE: Servlet.service() for servlet [login] in context with path [/WPISuite] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoClassDefFoundError: Could not initialize class edu.wpi.cs.wpisuitetng.ManagerLayer

Patch-set: 1
Reviewer: david.p.rubenstein@gmail.com <1002857@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1