Update patch set 3
Patch Set 3: Code-Review-1

SEVERE: Servlet.service() for servlet [login] in context with path [/WPISuite] threw exception [Servlet execution threw an exception] with root cause
java.lang.ClassNotFoundException: edu.wpi.cs.wpisuitetng.modules.taskmanager.model.BucketEntityManager

Patch-set: 3